### ISSUE TITLE
Saving a file with a SpikingPopulation module now clears the webui

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#19]
The file is saved and looks okay, but webui is cleared upon saving. The same happens when attempting to open a file with SpikingPopulation.
Attached a file with single SpikingPopulation

[sptst.ikg.txt](https://github.com/user-attachments/files/15544865/sptst.ikg.txt)

**Comment by ikaros-project** [comment]
Default values are not working properly which causes a crash. Explicitly setting parameters may work as a temporary fix See #21.

**Comment by trondarild** [comment]
Previously saved files can now be opened ok.
However: Started ikaros with path info like this:
./ikaros -DIKAROSPATH="/Users/trond/code/ikaros-3/"

Saving a SpikingPopulation ikg file still clears the graph
When path is included in the file like this, it is not loaded (graph is empty after load), but removing it makes it load ok:

<group -DIKAROSPATH="/Users/trond/code/ikaros-3/" name="Untitled" stop="-1" webui_port="8000">
...
</group>

**Comment by ikaros-project** [comment]
This is not supposed to work and causes an error because attributes are not allowed to start with a hyphen. An better eerror message should be added.

Instead, set variables directly at the command line or as an attribute as:

./ikaros IKAROSPATH="/Users/trond/code/ikaros-3/"

Or:

<group IKAROSPATH="/Users/trond/code/ikaros-3/">

However, the variable IKAROSPATH is not currently used by the kernel so although syntactically correct, this has no effect. Everything is saved in /UserData for the time being. Some mechanism to change the user directory may be added in the future.
