### ISSUE TITLE
Input matrix not stacking when multiple outputs are connected?

### ISSUE THREAD

**Issue by pierreklintefors** [ikaros-project/ikaros-3#34]
I suspect that multiple outputs connected to one input is not resulting in a stacked high-dimensional input matrix.
The info() function of the input matrix with 2 connections (each of size 19) gives:

> name = PositionInput
> rank = 1
> shape = 19 
> stride = 19 
> max_size = 19 
> size = 19
> offeset = 0
> labels = 
>    none
 
> data size = 19
> data = 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
#

**Comment by ikaros-project** [comment]
Automatic stacking was removed. Instead you have to do it explicitly in the connections. 

     <connection  source="A.OUTPUT" target="T.INPUT[0][]"/>
     <connection source="B.OUTPUT"target="T.INPUT[1][]"/>

[0][] means send output to new dimension with index 0 and use the size of the source for the second dimension.

Note that ranges must be set in the ikg since this is not supported by the WebUI yet and will sometimes be destroyed when saved from the WebUI. Working on it...

Also, the documentation needs to be updated.
