### ISSUE TITLE
Parameters of new module instances don't get default value

### ISSUE THREAD

**Issue by trondarild** [ikaros-project/ikaros-3#7]
Parameter values are left empty on new instances of a module even if default values are defined in ikc file.

**Comment by ikaros-project** [comment]
This intentional. If default values were filled in it would not be possible to define values in an outer group. However, the default values are still used in the actual module if they are not set anywhere.

The parameter value resolution first searches in the current module, then in all outer groups, and finally uses the default value if the parameter is not set in any of these places.
